//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Gameplay : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.gameplay_Move;
            }
        }
        
        public virtual SteamVR_Action_Single Grip
        {
            get
            {
                return SteamVR_Actions.gameplay_Grip;
            }
        }
        
        public virtual SteamVR_Action_Single Trigger
        {
            get
            {
                return SteamVR_Actions.gameplay_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.gameplay_Menu;
            }
        }
        
        public virtual SteamVR_Action_Boolean Thumb
        {
            get
            {
                return SteamVR_Actions.gameplay_Thumb;
            }
        }
        
        public virtual SteamVR_Action_Boolean TurnLeft
        {
            get
            {
                return SteamVR_Actions.gameplay_TurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean TurnRight
        {
            get
            {
                return SteamVR_Actions.gameplay_TurnRight;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.gameplay_Haptic;
            }
        }
    }
}
